# Use Node.js as the base image
FROM node:20.18.0-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy only the package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the development server uses
EXPOSE 3000

# Start the app with the development server
CMD ["npm", "run", "dev"]
 
